In [1]:
from lib.evaluate import Eva
from lib.utils import read_parameters

In [2]:
params = read_parameters('params/params_eva.json')

In [3]:
eva = Eva(params)
eva.read_benchmark_variants()
eva.read_method_variants()
eva.read_dicast_variants()
eva.overlap_benchmark()
#eva.confirm_variants()

[W::vcf_parse_info] INFO/END=94805 is smaller than POS at chr1:94816

In [7]:
eva.overlap_ids_methods[eva.overlap_ids_methods['id_2'] == 'gridss.DEL.37']

,id_1,chrom_1,start_1,end_1,size_1,id_2,chrom_2,start_2,end_2,size_2,distance,diff_start,diff_end,diff_size,tech,method,type
8124,chr1-1934990-DEL-595,chr1,1934988,1935583,595,gridss.DEL.37,chr1,1934928,1935589,661.0,0,60,6,0.900151,mgi,gridss,DEL

In [8]:
eva.overlap_ids_dicast[eva.overlap_ids_dicast['id_2'] == 'gridss.DEL.37']

Empty DataFrame
Columns: [id_1, chrom_1, start_1, end_1, size_1, id_2, chrom_2, start_2, end_2, size_2, distance, diff_start, diff_end, diff_size, tech, method, type]
Index: []

In [4]:
confirmed_method_ids = eva.method_variants.loc[eva.method_variants['confirmed'] == 1, 'id']

In [6]:
eva.dicast_variants.loc[(eva.dicast_variants['id'].isin(confirmed_method_ids)) & (eva.dicast_variants['confirmed'] == 0)]

,id,sample,tech,method,type,chrom,chrom2,start,end,size,filter,qual,pred_dicast,qual_dicast,confirmed
11990,manta.DEL.146,HG002_MGI,mgi,manta,DEL,chr1,NaN,108374852,108374967,115.0,PASS,373.000000,1,0.53,0
21477,gridss.DEL.12,HG002_MGI,mgi,gridss,DEL,chr1,NaN,934134,934135,1.0,LOW_QUAL,449.809998,0,0.20,0
21502,gridss.DEL.37,HG002_MGI,mgi,gridss,DEL,chr1,NaN,1934928,1934929,1.0,"LOW_QUAL, SINGLE_ASSEMBLY",205.660004,0,0.19,0
21523,gridss.DEL.58,HG002_MGI,mgi,gridss,DEL,chr1,NaN,2859238,2859239,1.0,LOW_QUAL,253.570007,0,0.13,0
21525,gridss.DEL.60,HG002_MGI,mgi,gridss,DEL,chr1,NaN,2960020,2960021,1.0,"LOW_QUAL, SINGLE_ASSEMBLY",103.040001,0,0.09,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74555,gridss.DEL.54228,HG002_MGI,mgi,gridss,DEL,chrX,NaN,151099692,151099693,1.0,PASS,1786.339966,0,0.31,0
74579,gridss.DEL.54252,HG002_MGI,mgi,gridss,DEL,chrX,NaN,153211152,153211153,1.0,PASS,513.799988,0,0.41,0
74592,gridss.DEL.54265,HG002_MGI,mgi,gridss,DEL,chrX,NaN,154519749,154519750,1.0,"LOW_QUAL, SINGLE_ASSEMBLY",168.929993,0,0.28,0
74596,gridss.DEL.54269,HG002_MGI,mgi,gridss,DEL,chrX,NaN,155057013,155057014,1.0,PASS,1106.859985,0,0.41,0
74631,gridss.DEL.4627,HG002_MGI,mgi,gridss,DEL,chr2,NaN,25004754,25004755,1.0,PASS,2338.919922,0,0.00,0

In [10]:
eva.method_variants[eva.method_variants['id'] == 'gridss.DEL.37']

,id,sample,tech,method,type,chrom,start,chrom2,end,size,filter,qual
22720,gridss.DEL.37,NA24385,mgi,gridss,DEL,chr1,1934928,NaN,1935589,661.0,"LOW_QUAL, SINGLE_ASSEMBLY",205.660004

In [26]:
1935589 - 1934928

661

In [11]:
eva.dicast_variants[eva.dicast_variants['id'] == 'gridss.DEL.37']

,id,sample,tech,method,type,chrom,chrom2,start,end,size,filter,qual,pred_dicast,qual_dicast
18161,gridss.DEL.37,HG002_MGI,mgi,gridss,DEL,chr1,NaN,1934928,1934929,1.0,"LOW_QUAL, SINGLE_ASSEMBLY",205.660004,0,0.19

In [12]:
16914119 - 16914129

-10

In [13]:
16914129  - 16914119

10

In [23]:
eva.benchmark_variants[eva.benchmark_variants['id'] == 'chr1-42277507-DEL-315']

,id,sample,tech,method,type,chrom,start,chrom2,end,size,filter,qual
488,chr1-42277507-DEL-315,NA24385,benchmark,benchmark,DEL,chr1,42277505,NaN,42277820,315,,None

In [25]:
eva.method_variants[eva.method_variants['id'] == 'manta.DEL.58']

,id,sample,tech,method,type,chrom,start,chrom2,end,size,filter,qual
13000,manta.DEL.58,NA24385,mgi,manta,DEL,chr1,42277505,NaN,42277820,315.0,PASS,199.0

In [17]:
648810 - 648867

-57

In [22]:
eva.benchmark_variants.head(60)

,id,sample,tech,method,type,chrom,start,chrom2,end,size,filter,qual
0,chr1-648811-DEL-57,NA24385,benchmark,benchmark,DEL,chr1,648809,NaN,648866,57,,None
1,chr1-820880-INS-245,NA24385,benchmark,benchmark,INS,chr1,820878,NaN,820879,245,,None
2,chr1-866852-INS-98,NA24385,benchmark,benchmark,INS,chr1,866850,NaN,866851,98,,None
3,chr1-876025-INS-2312,NA24385,benchmark,benchmark,INS,chr1,876023,NaN,876024,2312,,None
4,chr1-876301-INS-350,NA24385,benchmark,benchmark,INS,chr1,876299,NaN,876300,350,,None
5,chr1-909170-DEL-311,NA24385,benchmark,benchmark,DEL,chr1,909168,NaN,909479,311,,None
6,chr1-934065-DEL-812,NA24385,benchmark,benchmark,DEL,chr1,934063,NaN,934875,812,,None
7,chr1-964632-DEL-75,NA24385,benchmark,benchmark,DEL,chr1,964630,NaN,964705,75,,None
8,chr1-977066-INS-782,NA24385,benchmark,benchmark,INS,chr1,977064,NaN,977065,782,,None
9,chr1-977277-INS-245,NA24385,benchmark,benchmark,INS,chr1,977275,NaN,977276,245,,None
10,chr1-977846-INS-156,NA24385,benchmark,benchmark,INS,chr1,977844,NaN,977845,156,,None
11,chr1-996393-INS-330,NA24385,benchmark,benchmark,INS,chr1,996391,NaN,996392,330,,None
12,chr1-998758-INS-76,NA24385,benchmark,benchmark,INS,chr1,998756,NaN,998757,76,,None
13,chr1-1065021-INS-299,NA24385,benchmark,benchmark,INS,chr1,1065019,NaN,1065020,299,,None
14,chr1-1068825-INS-78,NA24385,benchmark,benchmark,INS,chr1,1068823,NaN,1068824,78,,None
15,chr1-1076228-DEL-418,NA24385,benchmark,benchmark,DEL,chr1,1076226,NaN,1076644,418,,None
16,chr1-1076240-INS-718,NA24385,benchmark,benchmark,INS,chr1,1076238,NaN,1076239,718,,None
17,chr1-1077707-DEL-322,NA24385,benchmark,benchmark,DEL,chr1,1077705,NaN,1078027,322,,None
18,chr1-1080917-INS-448,NA24385,benchmark,benchmark,INS,chr1,1080915,NaN,1080916,448,,None
19,chr1-1108886-INS-93,NA24385,benchmark,benchmark,INS,chr1,1108884,NaN,1108885,93,,None
20,chr1-1139253-DEL-854,NA24385,benchmark,benchmark,DEL,chr1,1139251,NaN,1140105,854,,None
21,chr1-1140156-INS-671,NA24385,benchmark,benchmark,INS,chr1,1140154,NaN,1140155,671,,None
22,chr1-1141364-INS-59,NA24385,benchmark,benchmark,INS,chr1,1141362,NaN,1141363,59,,None
23,chr1-1201779-INS-152,NA24385,benchmark,benchmark,INS,chr1,1201777,NaN,1201778,152,,None
24,chr1-1245159-INS-454,NA24385,benchmark,benchmark,INS,chr1,1245157,NaN,1245158,454,,None
25,chr1-1284172-INS-218,NA24385,benchmark,benchmark,INS,chr1,1284170,NaN,1284171,218,,None
26,chr1-1284172-INS-449,NA24385,benchmark,benchmark,INS,chr1,1284170,NaN,1284171,449,,None
27,chr1-1288346-DEL-842,NA24385,benchmark,benchmark,DEL,chr1,1288344,NaN,1289186,842,,None
28,chr1-1289188-INS-160,NA24385,benchmark,benchmark,INS,chr1,1289186,NaN,1289187,160,,None
29,chr1-1289710-DEL-237,NA24385,benchmark,benchmark,DEL,chr1,1289708,NaN,1289945,237,,None
30,chr1-1289848-INS-1173,NA24385,benchmark,benchmark,INS,chr1,1289846,NaN,1289847,1173,,None
31,chr1-1324173-INS-72,NA24385,benchmark,benchmark,INS,chr1,1324171,NaN,1324172,72,,None
32,chr1-1349975-DEL-1080,NA24385,benchmark,benchmark,DEL,chr1,1349973,NaN,1351053,1080,,None
33,chr1-1382626-INS-1390,NA24385,benchmark,benchmark,INS,chr1,1382624,NaN,1382625,1390,,None
34,chr1-1428121-INS-372,NA24385,benchmark,benchmark,INS,chr1,1428119,NaN,1428120,372,,None
35,chr1-1477855-INS-133,NA24385,benchmark,benchmark,INS,chr1,1477853,NaN,1477854,133,,None
36,chr1-1543726-INS-202,NA24385,benchmark,benchmark,INS,chr1,1543724,NaN,1543725,202,,None
37,chr1-1565631-INS-97,NA24385,benchmark,benchmark,INS,chr1,1565629,NaN,1565630,97,,None
38,chr1-1605523-DEL-60,NA24385,benchmark,benchmark,DEL,chr1,1605521,NaN,1605581,60,,None
39,chr1-1651422-DEL-53,NA24385,benchmark,benchmark,DEL,chr1,1651420,NaN,1651473,53,,None
40,chr1-1666975-DEL-167,NA24385,benchmark,benchmark,DEL,chr1,1666973,NaN,1667140,167,,None
41,chr1-1717605-DEL-51,NA24385,benchmark,benchmark,DEL,chr1,1717603,NaN,1717654,51,,None
42,chr1-1749606-INS-50,NA24385,benchmark,benchmark,INS,chr1,1749604,NaN,1749605,50,,None
43,chr1-1924224-INS-103,NA24385,benchmark,benchmark,INS,chr1,1924222,NaN,1924223,103,,None
44,chr1-1929385-INS-1031,NA24385,benchmark,benchmark,INS,chr1,1929383,NaN,1929384,1031,,None
45,chr1-1934990-DEL-595,NA24385,benchmark,benchmark,DEL,chr1,1934988,NaN,1935583,595,,None
46,chr1-1948935-INS-111,NA24385,benchmark,benchmark,INS,chr1,1948933,NaN,1948934,111,,None
47,chr1-1981713-INS-140,NA24385,benchmark,benchmark,INS,chr1,1981711,NaN,1981712,140,,None
48,chr1-1993705-INS-147,NA24385,benchmark,benchmark,INS,chr1,1993703,NaN,1993704,147,,None
49,chr1-2019221-INS-229,NA24385,benchmark,benchmark,INS,chr1,2019219,NaN,2019220,229,,None
50,chr1-2085678-INS-56,NA24385,benchmark,benchmark,INS,chr1,2085676,NaN,2085677,56,,None
51,chr1-2106635-DEL-175,NA24385,benchmark,benchmark,DEL,chr1,2106633,NaN,2106808,175,,None
52,chr1-2110022-DEL-95,NA24385,benchmark,benchmark,DEL,chr1,2110020,NaN,2110115,95,,None
53,chr1-2121507-DEL-162,NA24385,benchmark,benchmark,DEL,chr1,2121505,NaN,2121667,162,,None
54,chr1-2121699-DEL-260,NA24385,benchmark,benchmark,DEL,chr1,2121697,NaN,2121957,260,,None
55,chr1-2121986-DEL-928,NA24385,benchmark,benchmark,DEL,chr1,2121984,NaN,2122912,928,,None
56,chr1-2122142-DEL-340,NA24385,benchmark,benchmark,DEL,chr1,2122140,NaN,2122480,340,,None
57,chr1-2123471-INS-57,NA24385,benchmark,benchmark,INS,chr1,2123469,NaN,2123470,57,,None
58,chr1-2123661-INS-390,NA24385,benchmark,benchmark,INS,chr1,2123659,NaN,2123660,390,,None
59,chr1-2123798-INS-75,NA24385,benchmark,benchmark,INS,chr1,2123796,NaN,2123797,75,,None