In [1]:
from lib.evaluate import Eva
from lib.utils import read_parameters

import numpy as np
import plotly.express as px
import bioframe as bf
from tqdm import tqdm
import pandas as pd

# Functions

In [7]:
def plot_precision_recall_curve(df, svtype):
    """ Plot precision recall curve. 

    param pr_rc_df: pandas dataframe with precision and recall for different thresholds """

    pr_rc_df = df[df['type'] == svtype].copy().reset_index(drop=True)

    CB_color_cycle = ['black', '#377eb8', '#ff7f00', '#4daf4a',
                  '#f781bf', '#a65628', '#984ea3',
                  '#999999', '#e41a1c', '#dede00']
    circle_bg_white = [0, 0, 0, 1, 1, 1, 1]
    fig = px.line(x='recall', y='precision', color='method', 
                data_frame=pr_rc_df, 
                color_discrete_sequence=CB_color_cycle)


    #for i, method in enumerate(self.variants.keys()):
    #    x = pr_rc_df[pr_rc_df['method'] == method].reset_index(drop=True).loc[0, 'recall']
    #    y = pr_rc_df[pr_rc_df['method'] == method].reset_index(drop=True).loc[0, 'precision']
    #    if circle_bg_white[i] == 1:
    #        fig.add_shape(type='circle', xref='x', yref='y', x0=x-0.002, y0=y-0.015, x1=x+0.003, y1=y+0.005, line_color=colors[i], line_width=2, opacity=1, fillcolor='white')
    #    else:
    #        fig.add_shape(type='circle', xref='x', yref='y', x0=x-0.002, y0=y-0.015, x1=x+0.003, y1=y+0.005, line_color=colors[i], line_width=2, opacity=1, fillcolor=colors[i])


    fig.update_layout(plot_bgcolor='white', xaxis_title='Recall', yaxis_title='Precision', xaxis_linecolor='black', yaxis_linecolor='black')
    fig.update_traces(line=dict(width=2))
    fig.update_xaxes(ticks='outside', tickcolor='black', tickwidth=1, ticklen=5, gridcolor='lightgray', gridwidth=0.5, range=[0, 1.1])
    fig.update_yaxes(ticks='outside', tickcolor='black', tickwidth=1, ticklen=5, gridcolor='lightgray', gridwidth=0.5, range=[0, 1.1])
    fig.show()

# Script

In [3]:
params = read_parameters('params/giab/params_eva.json')

In [4]:
eva = Eva(params)
eva.read_benchmark_variants()
eva.read_method_variants()
eva.read_dicast_variants()
eva.overlap_bench_dicast()
eva.overlap_bench_methods()
eva.compute_precision_recall_df()

In [9]:
eva.precision_recall_df

         method  precision    recall type
0        dicast   0.325136  0.466087  DEL
1        dicast   0.366831  0.465863  DEL
2        dicast   0.393888  0.465863  DEL
3        dicast   0.415506  0.465752  DEL
4        dicast   0.432943  0.465640  DEL
...         ...        ...       ...  ...
41427    gridss   0.000000  0.000000  DEL
41428    gridss   0.000000  0.000000  DEL
41429    gridss   1.000000  0.000000  DEL
41430  cnvnator   0.084551  0.021307  DEL
41431  cnvnator   1.000000  0.000000  DEL

[41432 rows x 4 columns]

In [8]:
plot_precision_recall_curve(eva.precision_recall_df, 'DEL')

In [10]:
eva.variants['dicast'][(eva.variants['dicast']['confirmed'] == 0) & (eva.variants['dicast']['qual'] > 0.4)]

,id,chrom,start,end,type,size,confirmed,qual
8976,dicast.DEL.16,chr1,2123365,2124337,DEL,972.0,0,0.57
9038,dicast.DEL.80,chr1,4064688,4066277,DEL,1589.0,0,0.69
9040,dicast.DEL.82,chr1,4135862,4136499,DEL,637.0,0,0.44
9050,dicast.DEL.93,chr1,5817458,5817532,DEL,74.0,0,0.61
9062,dicast.DEL.106,chr1,14109814,14111750,DEL,1936.0,0,0.96
...,...,...,...,...,...,...,...,...
70171,dicast.DEL.73798,chrX,95139001,95141000,DEL,1999.0,0,0.82
70174,dicast.DEL.73802,chrX,115403001,115405000,DEL,1999.0,0,0.53
70177,dicast.DEL.73805,chrX,116556001,116595000,DEL,38999.0,0,0.54
70180,dicast.DEL.73809,chrX,125272001,125281000,DEL,8999.0,0,0.70
70185,dicast.DEL.73814,chrX,143653001,143659000,DEL,5999.0,0,0.66

In [12]:
eva.variants['dicast'][(eva.variants['dicast']['confirmed'] == 1) & (eva.variants['dicast']['qual'] < 0.4)].head(40)

,id,chrom,start,end,type,size,confirmed,qual
17,chr1-108374900-DEL-80,chr1,108374899,108374979,DEL,80.0,1,0.17
119,chr1-2121986-DEL-928,chr1,2121985,2122913,DEL,928.0,1,0.10
122,chr1-212910886-DEL-1942,chr1,212910885,212912827,DEL,1942.0,1,0.08
211,chr1-3299545-DEL-732,chr1,3299544,3300276,DEL,732.0,1,0.17
227,chr1-5246622-DEL-70,chr1,5246621,5246691,DEL,70.0,1,0.17
341,chr10-1209420-DEL-90,chr10,1209419,1209509,DEL,90.0,1,0.30
379,chr10-133648327-DEL-61,chr10,133648326,133648387,DEL,61.0,1,0.11
386,chr10-18561029-DEL-362,chr10,18561028,18561390,DEL,362.0,1,0.14
428,chr10-417697-DEL-409,chr10,417696,418105,DEL,409.0,1,0.21
477,chr10-735403-DEL-423,chr10,735402,735825,DEL,423.0,1,0.30
761,chr12-131366871-DEL-486,chr12,131366870,131367356,DEL,486.0,1,0.17
762,chr12-131396043-DEL-54,chr12,131396042,131396096,DEL,54.0,1,0.34
763,chr12-131428727-DEL-482,chr12,131428726,131429208,DEL,482.0,1,0.14
767,chr12-132148963-DEL-1139,chr12,132148962,132150101,DEL,1139.0,1,0.06
768,chr12-132232447-DEL-2732,chr12,132232446,132235178,DEL,2732.0,1,0.08
797,chr12-33232170-DEL-13195,chr12,33232169,33245364,DEL,13195.0,1,0.28
853,chr12-80180154-DEL-160,chr12,80180153,80180313,DEL,160.0,1,0.39
887,chr13-104653982-DEL-728,chr13,104653981,104654709,DEL,728.0,1,0.26
908,chr13-113812920-DEL-54,chr13,113812919,113812973,DEL,54.0,1,0.09
939,chr13-35763068-DEL-54,chr13,35763067,35763121,DEL,54.0,1,0.31
940,chr13-35763228-DEL-73,chr13,35763227,35763300,DEL,73.0,1,0.31
979,chr13-60712290-DEL-1065,chr13,60712289,60713354,DEL,1065.0,1,0.08
1053,chr14-105617823-DEL-56,chr14,105617822,105617878,DEL,56.0,1,0.33
1055,chr14-20082548-DEL-4663,chr14,20082547,20087210,DEL,4663.0,1,0.30
1080,chr14-37300428-DEL-1445,chr14,37300427,37301872,DEL,1445.0,1,0.26
1167,chr15-23426245-DEL-3807,chr15,23426244,23430051,DEL,3807.0,1,0.10
1356,chr16-88534247-DEL-75,chr16,88534246,88534321,DEL,75.0,1,0.34
1364,chr16-960401-DEL-864,chr16,960400,961264,DEL,864.0,1,0.04
1425,chr17-46277755-DEL-4456,chr17,46277754,46282210,DEL,4456.0,1,0.19
1520,chr18-14822943-DEL-363,chr18,14822942,14823305,DEL,363.0,1,0.20
1662,chr19-35360248-DEL-12468,chr19,35360248,35372716,DEL,12468.0,1,0.09
1713,chr19-54738891-DEL-59,chr19,54738890,54738949,DEL,59.0,1,0.35
1745,chr2-105209435-DEL-2535,chr2,105209434,105211969,DEL,2535.0,1,0.33
1779,chr2-125650697-DEL-72,chr2,125650696,125650768,DEL,72.0,1,0.32
1789,chr2-1343156-DEL-2041,chr2,1343155,1345196,DEL,2041.0,1,0.00
1821,chr2-159102288-DEL-2269,chr2,159102287,159104556,DEL,2269.0,1,0.11
2222,chr22-16344806-DEL-59,chr22,16344805,16344864,DEL,59.0,1,0.00
2223,chr22-16357136-DEL-50,chr22,16357135,16357185,DEL,50.0,1,0.01
2224,chr22-16564443-DEL-68,chr22,16564442,16564510,DEL,68.0,1,0.29
2265,chr22-40398220-DEL-1019,chr22,40398219,40399238,DEL,1019.0,1,0.37